

spring.application.name=sb-ecom
project.image = images/
server.forward-headers-strategy=framework

spring.datasource.url = jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username = postgres
spring.datasource.password = srikanth@123
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=mySecretKey123123456789kfbsfbblBFAFjbfbdakvkjvj
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=SpringBootEcom




